### PR TITLE
Proposed changes to the Bylaws

### PR DESCRIPTION
**Pull request by ivanaszuber**
- Proposed addendum for disqualifying non-viable candidates from election.
- Removed Industry Directors from the board (replaced with Community Directors)

### CODE REVIEW

**Comment by ivanaszuber** [comment]
Current members of the board (Robby Dermody, Adam Krellenstein, Chris Derose, Tom Ding and Jeremy Lam) please vote on these changes.

**Comment by robby-dermody** [comment]
ACK

**Comment by brighton36** [comment]
ACK

**Comment by adamkrellenstein** [comment]
ACK

**Comment by pulman4973** [comment]
ack

**Comment by ScroogeMcDuckButWithBitcoin** [comment]
ack

**Comment by robby-dermody** [comment]
(This has already been merged :)

**Pull request merged**
