### PR TITLE
Add content policy

### PR DESCRIPTION
**Pull request by robby-dermody**
I would like to move for a board vote on the attached content policy, which shall have effect over the counterparty slack chat and counterpartytalk.

Please conduct a final review, and give an AYE or NAY.

### CODE REVIEW

**Comment by jdogresorg** [comment]
AYE

**Comment by robby-dermody** [comment]
AYE

**Comment by CounterpartyMatt** [comment]
aye

**Comment by trevorxcp** [comment]
AYE

**Pull request merged**
