### PR TITLE
draft anti rollback provision

### PR DESCRIPTION
**Pull request by robby-dermody**
This language is for proposal. Feel free to suggest alternative language.

@rubensayshi @CounterpartyMatt @trevorxcp @jdogresorg @cointea1121 @adamkrellenstein 

Board members: If in favor, please provide an AYE vote so we can merge. Require a simple majority.

### CODE REVIEW

**Comment by robby-dermody** [comment]
AYE

**Comment by jdogresorg** [comment]
AYE

**Comment by CounterpartyMatt** [comment]
aye

**Comment by trevorxcp** [comment]
AYE

**Pull request merged**
