### PR TITLE
Updated bitcoin core version

### PR DESCRIPTION
**Pull request by rippler**

### CODE REVIEW

**Comment by ivanaszuber** [comment]
Is this official? Should everyone upgrade to 0.10.1?

**Comment by rippler** [comment]
Not official yet, but I tested that it works so it's okay to mention it I think.
You can leave the PR unacceptable for a while if you want.

**Comment by rippler** [comment]
Not official yet, but I tested that it works so it's okay to mention it I think.
You can leave the PR unaccepted for a while if you want.

**Comment by ivanaszuber** [comment]
Yeah, I think it's fine, but I'll leave this one for @adamkrellenstein to merge

**Comment by adamkrellenstein** [comment]
We need to wait for more testing to be done.

**Comment by rippler** [comment]
Note that the current CP docs point to the generic "releases" page where all releases are listed, and if anyone goes that (s)he will get the latest. 
If we want to be specific we could recommend a specific release, but we'd have to remember to update that info as we move forward.

**Comment by adamkrellenstein** [comment]
See 8c999d0eb7953fe81d1e6f563be2a29e63773874

**Pull request closed without merging**
