### PR TITLE
Update API Documentation

### PR DESCRIPTION
**Pull request by ouziel-slama**
comes with https://github.com/CounterpartyXCP/counterparty-core/pull/1799

### CODE REVIEW

**Review by adamkrellenstein — APPROVED** [review]
how much of this is a duplicate of https://github.com/CounterpartyXCP/counterparty-core/blob/tweakapi/counterparty-core/tools/apidoc/blueprint-template.md?

**Comment by ouziel-slama** [comment]
> how much of this is a duplicate of https://github.com/CounterpartyXCP/counterparty-core/blob/tweakapi/counterparty-core/tools/apidoc/blueprint-template.md?

nothing duplicate :) `genapidoc.py` generate both `apiary.apib` and `node-api.md` from `blueprint-template.md`.

**Comment by adamkrellenstein** [comment]
Maybe we should add a comment "Generated by `genapidoc.py` on $DATE` etc.

**Comment by ouziel-slama** [comment]
> Maybe we should add a comment "Generated by `genapidoc.py` on $DATE` etc.

good idea! done!

**Pull request merged**
