### PR TITLE
pip install command for Win

### PR DESCRIPTION
**Pull request by rippler**

### CODE REVIEW

**Comment by adamkrellenstein** [comment]
@rippler, not `pip3` (just to be safe)?

**Comment by rippler** [comment]
@adamkrellenstein: yes, on Windows `pip` is enough because it doesn't come with preinstalled Python 2.x and besides, even if Python 2.x is installed, it won't matter (`pip` will default to `pip` from Python 3.x) as long as Python 3 is in one's system `PATH` (which I think should be the case for people who choose to run `counterparty-lib`).
```
C:\Python34\Scripts>pip3 -V
pip 1.4.1 from c:\python34\lib\site-packages\pip-1.4.1-py3.4.egg (python 3.4)
C:\Python34\Scripts>pip -V
pip 1.4.1 from c:\python34\lib\site-packages\pip-1.4.1-py3.4.egg (python 3.4)
```

For Ubuntu 14.04, `sudo pip3` should be used and that should be updated.

**Comment by adamkrellenstein** [comment]
I think we should always use `pip3`, just in case, across all systems.

**Comment by rippler** [comment]
Sounds good. I was wondering if I should use pip3, but I thought I'd just follow the Linux precedent in the same doc :-)

**Pull request merged**
