### PR TITLE
Added architecture file

### PR DESCRIPTION
**Pull request by ivanaszuber**

### CODE REVIEW

**Comment by ivanaszuber** [comment]
Can we use this as a starting point @adamkrellenstein ?

**Comment by robby-dermody** [comment]
+1 from me, makes sense to have a high level arch document (include the diagrams we have as well?)...then we can remove this part from the fed node doc and reference this doc instead

**Comment by adamkrellenstein** [comment]
Looks good! I'd just move `counterblock` to after Counterwallet and merge. :)

**Comment by ivanaszuber** [comment]
done, @robby-dermody the diagram was already in there. I'll remove those parts from federated node and add a link

**Pull request merged**
