### PR TITLE
remove industry and founding members, plus other cleanup

### PR DESCRIPTION
**Pull request by robby-dermody**
as I am resigning, I would like the board to vote on these changes to the bylaws. These changes remove the industry and founding members, plus include other cleanup.

### CODE REVIEW

**Comment by jdogresorg** [comment]
Perhaps change :
text = XCPELECTION + Candidate Number
to
text = XCPELECTION + YEAR + Candidate Number ( ex: XCPELECTION2017 1 )

Other than that suggestion, looks good to me :)

**Comment by ShawnLeary** [comment]
+1

**Comment by robby-dermody** [comment]
ACK

**Comment by jdogresorg** [comment]
Looks good to me. ACK :)

**Comment by sull** [comment]
ACK

**Comment by deweller** [comment]
We have approval from a majority of the current board of directors.

**Pull request merged**
