### PR TITLE
Update assets.md

### PR DESCRIPTION
**Pull request by zerog975**
Add info reg. different wallets, and update the asset information to reflect CIP0003

### CODE REVIEW

**Comment by davestaxcp** [comment]
Because of the easy mess up a user can do when seeing "versions of Freewallet" and trying to find the wrong version I think it is important to include this as "Freewallet.io"

**Comment by davestaxcp** [comment]
new commit looks good to me as far as information goes for the main recommended wallets by devs/community

**Comment by davestaxcp** [comment]
On second thought I'm thinking it would be better to change this:

`Counterwallet, rpw.wtf, or the desktop or mobile versions of Freewallet. Casual` ...

to this:

"[Counterwallet.io](https://counterwallet.io/) , [rpw.wtf](https://rpw.wtf/) , or the desktop or mobile versions of [Freewallet.io](https://freewallet.io/) . Casual"  ...

There is a non recommended version of 'Freewallet' that is not at all associated with Counterparty or Jdog and I think it is important to be specific here.

Case and point for this reasoning lies here in this account warning people not to use the wrong version of Freewallet (which is not uncommon for new users mess up):
https://forums.counterparty.io/u/freewalletscam/summary

I've known some people who just search "Freewallet" on some app store or search engine that does not return the correct Freewallet.io wallet....

**Comment by adamkrellenstein** [comment]
Removed these references to defunct wallets.

**Pull request closed without merging**
